# Copyright 2023 shadow3aaa@gitbub.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "fas-rs"
version = "3.5.0"
edition = "2021"
description = "Frame aware scheduling for android. Requires kernel ebpf support."
authors = ["shadow3"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/shadow3aaa/fas-rs"

[dependencies]
likely_stable = "0.1.2"
parking_lot = "0.12.3"
log = "0.4.22"
anyhow = { version  = "1.0.89", features = ["backtrace"] }
thiserror = "1.0.63"
inotify = { version = "0.11.0", default-features = false }
libc = "0.2.158"
flexi_logger = "0.29.0"
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
sys-mount = { version = "3.0.1", default-features = false }
quick-xml = { version = "0.36.2", features = ["serialize"] }
mlua = { version = "0.9.9", features = ["luajit", "vendored"] }
frame-analyzer = "0.2.7"
dumpsys-rs = { git = "https://github.com/shadow3aaa/dumpsys-rs" }
mimalloc = "0.1.43"
num_cpus = "1.16.0"
rand = "0.8.5"
rusqlite = { version = "0.32.1", features = ["bundled"]}

[build-dependencies]
anyhow = "1.0.89"
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[profile.dev]
overflow-checks = false
opt-level = 3
strip = true

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true

